### ISSUE TITLE
No actual use of auth0

### ISSUE THREAD

**Issue by rosenk** [kmaida/auth0-elm-with-jwt-api#1]
Instead there is just a misterious api url. The project seems unfinished

**Comment by kmaida** [comment]
You are correct, this project does not use Auth0. The "auth0" name of the repo references the fact that this repo is a companion to the Auth0 blog posts. This repo is Elm with JWT and an API. The repo that has Auth0 implemented is this one: https://github.com/kmaida/elm-with-auth0

Please note that it is version 0.17 of Elm.
